### ISSUE TITLE
Library versions

### ISSUE THREAD

**Issue by galfaroth** [naokishibuya/car-behavioral-cloning#1]
Could you please include the tensorflow and keras library versions in environments? I have compile errors in drive.py because of incompatibility of the model.

**Comment by naokishibuya** [comment]
Hi @galfaroth 
I've updated the environment-gpu.yml and environment.yml.  The tensorflow and keras versions are 1.1 and 1.2 respectively.  Let me know if that works for you.

**Comment by galfaroth** [comment]
Thank you so much for clarifying that!

**Comment by naokishibuya** [comment]
no problem :)
