### ISSUE TITLE
how does the model run rgb2yuv?

### ISSUE THREAD

**Issue by aneesh-joshi** [naokishibuya/car-behavioral-cloning#11]
I notice you are doing a color space change to yuv while training.
However, it isn't implemented as a keras layer (like Cropping2D) 
So, when you export the model and run it in the unity simulator, the model uses RGB itself.

Am I missing something here?

Thanks

**Comment by naokishibuya** [comment]
hi @aneesh-joshi 

In the drive.py, I'm calling the `util.preprocess` method before calling `predict` on the model.

```python
image = utils.preprocess(image) # apply the preprocessing
```
This function internally calls `rgb2yuv`.  So, the model is seeing the same color space as in training.

**Comment by aneesh-joshi** [comment]
Ah.
Thanks for the response, @naokishibuya 
:)
