### ISSUE TITLE
arc tan activation in last layer

### ISSUE THREAD

**Issue by naveen7v** [naokishibuya/car-behavioral-cloning#12]
Hi, 

I saw the same NVIDIA model by Lex Fridman (from MIT) they used the arctan activation function in the final layer ,to bound the outputs between -20 and 20 and 'Relu' for the previous layers

you have a linear activation for the last and 'elu' for the previous layers , any reason for this or will both methods work fine?

**Comment by naokishibuya** [comment]
Hi @naveen7v
I imagine those parameters will all work as long as you train it carefully.  I did not try all these different activation functions, so I am not 100% sure.  I think you would need to try it for yourself to find out!
