### ISSUE TITLE
Why YUV?

### ISSUE THREAD

**Issue by nikhilt44** [naokishibuya/car-behavioral-cloning#16]
Hi,

I was curious to know if there's any specific reason why you converted the RGB image to YUV?

**Comment by naokishibuya** [comment]
hi @nikhilt44 
The original NVIDIA article uses YUV for their behavior cloning project.
https://devblogs.nvidia.com/deep-learning-self-driving-cars/
My understanding is that YUV separates the brightness information (Y - less important) from the color information (UV - more important) which makes it easier for the network to learn.  
But I'd expect RBG would also work well as long as trained well (I have not tried).
