### ISSUE TITLE
ask throttle in drive.py

### ISSUE THREAD

**Issue by mifikri** [naokishibuya/car-behavioral-cloning#21]
i wanna clarify the formula of throttle in drive.py
throttle = 1.0 - steering_angle**2 - (speed/speed_limit)**2, Why did you do that? How the throttle is connected to the steering angle?﻿ can you explain this?

**Comment by naokishibuya** [comment]
@mifikri It's just a heuristic rule to reduce the throttle when the steering angle is larger to prevent the car from drifting.
