### ISSUE TITLE
"GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 404

### ISSUE THREAD

**Issue by matthewgan** [naokishibuya/car-behavioral-cloning#22]
I just open up the udacity simulator, and clone this repo trying to get a test run
when i run
python drive.py model.h5
I got this printing all over the terminal:
127.0.0.1 - - [06/Dec/2018 23:56:52] "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 404 342 0.002979
(17772) accepted ('127.0.0.1', 56738)
and its keep printing like this

Please kindly help to tell me what am i be wrong with?

**Comment by naokishibuya** [comment]
@matthewgan I am not sure what is wrong here.  My suggestion would be to make sure the environment set up properly using environments.yml or environments-gpu.yml using the conda command (see the README for details) if you have not done so.

**Comment by russelldj** [comment]
I found a solution [here](https://github.com/llSourcell/How_to_simulate_a_self_driving_car/issues/34#issuecomment-445077710). They just suggest uninstalling the python-socketio and reinstalling it with pip. It worked for me.
