### ISSUE TITLE
https://github.com/car-behavioral-cloning

### ISSUE THREAD

**Issue by shweta7p** [naokishibuya/car-behavioral-cloning#4]
Hello,
 I got following error when running the drive.py script
usage: drive.py[-h] model [image folder]
drive.py: error: the following arguments are required: model

**Comment by naokishibuya** [comment]
Hi @shweta7p 

When you run the drive.py, you'll need to pass the model file name like below:

```
python drive.py model.h5
```

Let me know if that works for you.

**Comment by shweta7p** [comment]
@naokishibuya: thanks for the reply, i have run " python drive.py model.h5". Now, it showing this message 

![Uploading Capture.PNG…]()

and it stuck at the last line.

**Comment by naokishibuya** [comment]
Hi @shweta7p 
I have no idea where that message comes from..  :(
Is there anything else you saw that could give us some hints to figure out what happened?

**Comment by naokishibuya** [comment]
Hello @shweta7p 
I'm closing this issue as I haven't heard from you for some time.  I hope you found a solution to the issue but if you have more details to discuss, please reopen the issue and we can further examine the issue.

**Comment by AladdinDorado** [comment]
Dear Sir:
When i run the drive.py i got this error.  Please help.

usage: drive.py [-h] model [image_folder]
drive.py: error: the following arguments are required: model
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2
