### ISSUE TITLE
The model.h5 is not working as expected.

### ISSUE THREAD

**Issue by chaitanyya** [naokishibuya/car-behavioral-cloning#5]
We tried to run the model.h5 file and for some reason, it always crashes at the first turn in the jungle track. Is it the model you used in the video?

**Comment by naokishibuya** [comment]
Yes, the file was used for the video.  One possible cause for the crash might be the library version differences.  environment.yml or environment-gpu.yml has the conda environment details.  Let me know if you still have the issue even though the environment is the same.

**Comment by shahidul56** [comment]
Same problem i faceed; i installed all package manually with pip and the model don't work 

@chaitanyya  you can try this

First you need to 
1. open anaconda promt as adminstrator 
2. write `conda env list `
![ferrthrth](https://user-images.githubusercontent.com/11449967/34458796-429f2338-ee09-11e7-8a85-25f5be2241cb.PNG)

see that if the previous env with name "car-behavioral-cloning" has existed there then delete it  

with `conda remove --name car-behavioral-cloning --all`

3. Now 
![wef](https://user-images.githubusercontent.com/11449967/34458806-a1533770-ee09-11e7-8e2d-9dac8412f385.PNG)

write `anaconda login`  for log into the anaconda server, give username and pass , or no package will be downloaded 

4. write `cd /d H:\How_to_simulate_a_self_driving_car ` here place  your won gitclone directory 

5. Now Write `conda env create -f environment.yml ` 

6. activate the new env with `activate car-behavioral-cloning`

![dwqwdq](https://user-images.githubusercontent.com/11449967/34458862-dae5d644-ee0b-11e7-82c9-c6a519c204eb.PNG)

7. Now write `python drive.py model.h5`

thanks  @naokishibuya  code works superbly fine ..
