### ISSUE TITLE
Hi there is no return in the utils.py file ?

### ISSUE THREAD

**Issue by jhasuman** [naokishibuya/car-behavioral-cloning#6]
While I was trying to understand the utils.py file but there is no return for the last function, Am I missing something ? Thank You!!

**Comment by naokishibuya** [comment]
Hi @jhasuman 
That function is a generator.  The 'yield' returns values but the function itself does not return/exit.
If you search for 'Python generator' or 'Keras fit_generator', you should be able to find related articles.  For example, 
- https://jeffknupp.com/blog/2013/04/07/improve-your-python-yield-and-generators-explained/
- https://medium.com/@fromtheast/implement-fit-generator-in-keras-61aa2786ce98

**Comment by naokishibuya** [comment]
@jhasuman - I'm closing this for now.  Let me know if you need any further clarification.
