### ISSUE TITLE
Data 

### ISSUE THREAD

**Issue by saig07** [naokishibuya/car-behavioral-cloning#8]
Hi Sir,

I currently have about ~64 000 images in my dataset and the performance of my model is not very good. Could this be due to the fact that the model is overfitting?

**Comment by naokishibuya** [comment]
Hi @saig07 
It's hard to say.  I had a similar experience when I recorded quite a lot of training images.  My approach was to add training images incrementally.  For example, you do one lap with driving in the center.  Then, record some more driving cases (i.e. a sharp corner that the car is not handling well.  a recovery case when a car is driving near the left/right edge and then returns to the center.  etc.).  If adding that to your training set makes the performance worse, remove it (or restore the original training set).  You should need only one or two laps with center driving and a handful difficult cases to make the car run reasonably well in the lake scene.

**Comment by saig07** [comment]
Thank you, I will try that approach and keep you updated.

**Comment by saig07** [comment]
![screenshot 8](https://user-images.githubusercontent.com/32597950/31442090-8c081b14-ae95-11e7-88b8-97bb8355b9af.png)


I have done what you suggested and the performance on the lake track is much better, however, 

when testing the model on the jungle track it keeps getting stuck at this point

**Comment by saig07** [comment]
I have tried your approach and my model works much better in the lake track, however, it keeps getting stuck at the point shown in the screenshot.
![screenshot 8](https://user-images.githubusercontent.com/32597950/31442283-2f52a834-ae96-11e7-953e-735101ef4259.png)

**Comment by naokishibuya** [comment]
It's been awhile but looking at my own video - I think I recorded so that the car drives on the left side before approaching that curve (which is right after the downslope) to give enough space to turn left.

https://youtu.be/mZOc-zrbnR8?t=1m11s

You'll need to experiment more with the jungle track.  enjoy :)

**Comment by saig07** [comment]
I am thinking of adding an LSTM layer to the current model, would you be able to advise on that?

**Comment by naokishibuya** [comment]
I haven't tried such architecture myself.  You can probably search for similar ideas.  good luck!
